#!/bin/bash

mkdir  -p jobs/ug1

for language in "$@"
do
    timestamp="$(date +"%F_%T")"
    EXPORT=jobs/ug1/"$language"_$timestamp
    echo "Output will be sent to $EXPORT"
    echo "WARNING: deleting $EXPORT"
    rm $EXPORT

    export PYTHONIOENCODING=utf-8

    python driver.py $language incremental --universal experimentOutputs/ug1.p -t 100 --timeout 24.0 --geometry  > $EXPORT 2>&1 
done
